### PR TITLE
Castlepy3

### PR DESCRIPTION
**Pull request by agitator**

### CODE REVIEW

**Comment by vangheem** [comment]
Ouch, py 3.6 wasn't running just because of the bad merge here? https://github.com/repoze/repoze.catalog/pull/12/commits/db5be32e896a6f6703207a318cb11bf0972286dd

Looks fine to me.

**Comment by agitator** [comment]
@tseaver all good now? merge and release?

**Comment by agitator** [comment]
@tseaver ping?

**Comment by agitator** [comment]
@mcdonc ping?

**Comment by agitator** [comment]
@chrisrossi @hathawsh

**Comment by agitator** [comment]
anyone?

**Comment by agitator** [comment]
@tseaver ping, all green now ;-)

**Comment by agitator** [comment]
@tseaver ping?

**Comment by davisd50** [comment]
I'm looking to bake the catalog into a project I'm doing....this looks like an effort to bring Py3 support into play. awesome.  Does this feel like it close to another release to pypi?

**Comment by mcdonc** [comment]
> I'm looking to bake the catalog into a project I'm doing....this looks like an effort to bring Py3 support into play. awesome. Does this feel like it close to another release to pypi?

Please don't use this, it's an earlier iteration of Hypatia: https://hypatia.readthedocs.io/en/latest/index.html  .  There is no reason to use this software in a greenfield project.

**Comment by jensens** [comment]
This information should be added to the the Readme.

For some of our projects a release of repoze.catalog working in python 3 would save us complex and time consuming migration work. It is more than good enough for what we need.

**Comment by jensens** [comment]
@mcdonc Hypatia Readme and docs says it is still alpha. How can this be an alternative then? repoze.catalog is mature and field tested.

**Comment by mcdonc** [comment]
> @mcdonc Hypatia Readme and docs says it is still alpha. How can this be an alternative then? repoze.catalog is mature and field tested.

Apologies, you're right, it's not really my place to tell you which software to use.  I'll rephrase what I mean.  Neither I not Tres wants to maintain repoze.catalog. Neither of us uses it at all.  If someone else steps up to maintain it, which means ensuring its tests pass, gatekeeping pull requests, making new releases, etc, I would grant them all the requisite power to do so .

There is an alternative in hypatia, that, although marked alpha, is a continuation of the work done in repoze.catalog.  I personally do care about hypatia.

**Comment by jensens** [comment]
@mcdonc it is ok for me and @agitator to take the role of a maintainer. We need repoze.catalog now and the next years. Both of us are having some years experience maintaining packages. PyPI usernames are _jensens_ and _hpeteragitator_. 

_Hypatia_ really looks good and probably is what I'd take for a new project. However, the alpha state does not invite people to use it. Alpha usually means API may change, features can come and go, and its not meant for production. 
Also, there is no TODO list and there are only 3 issues, so it is difficult to get an idea what is missing. The issues are not dealing with in-depth problems. If it is ready it should be re-released as final.

**Comment by mcdonc** [comment]
> @mcdonc it is ok for me and @agitator to take the role of a maintainer. We need repoze.catalog now and the next years. Both of us are having some years experience maintaining packages. PyPI usernames are _jensens_ and _hpeteragitator_.

Great, you are both now maintainers on PyPI and have direct commit access to this repo.

> _Hypatia_ really looks good and probably is what I'd take for a new project. However, the alpha state does not invite people to use it. Alpha usually means API may change, features can come and go, and its not meant for production.

Probably true, but I can tell you as the winner of the most-commits lottery that this repo is old and busted and hypatia is slightly less old and busted ;)

> Also, there is no TODO list and there are only 3 issues, so it is difficult to get an idea what is missing. The issues are not dealing with in-depth problems. If it is ready it should be re-released as final.

I hope my say-so will suffice in the meantime.

**Comment by jensens** [comment]
@mcdonc thank you, but it seems I still have no write permission on this repository.

**Comment by mcdonc** [comment]
> @mcdonc thank you, but it seems I still have no write permission on this repository.

You do now, sorry.

**Comment by jensens** [comment]
works :)

**Comment by WuShell** [comment]
> 
> Apologies, you're right, it's not really my place to tell you which software to use. I'll rephrase what I mean. Neither I not Tres wants to maintain repoze.catalog. Neither of us uses it at all. If someone else steps up to maintain it, which means ensuring its tests pass, gatekeeping pull requests, making new releases, etc, I would grant them all the requisite power to do so .
> 

Definetely sad news to read about project maintainership. 

I also agree that it would be nice if somebody adds the reference both to the project not being maintained (or looking for maintainer) and some info about hypatia being a newer version/next iteration of the idea of a catalog for ZODB.

And finally, I'm wondering now about the other repoze.* projects, are they in the same state? (I just have a pending (bugfix) PR in repoze.sendmail, for example)

**Pull request merged**
